### ISSUE TITLE
GM_xmlhttpRequest is not defined

### ISSUE THREAD

**Issue by zman0900** [drakeapps/synccit-browser-extension#4]
When using version 1.5 of the addon available at addons.mozilla.org, synccit does not function and prints the following error when firefox is run from a terminal:

```
console.error: synccit: 
  Message: ReferenceError: GM_xmlhttpRequest is not defined
  Stack:
    @resource://gre/modules/XPIProvider.jsm -> jar:file:///home/dan/.mozilla/firefox/kcm956bf.default/extensions/jid1-rbAJu4BHjMqTww@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://ae1eba58-4e65-48ae-8436-d93346bd059d/synccit/data/synccit.js:139
```

Compiling the script as explained in the readme produces a working addon (as of 67e710b82a81351eb10afca46d2cb5f56f1b930a).  Running as a greasemonkey script also works fine.
